blank_issues_enabled: false

contact_links:
  - name: â“ Join Our Discord Server
    url:  https://discord.gg/q4d3ggrFVA
    about: "Let us help you if you hit a roadblock!"

  - name: ğŸ“– Read the Docs
    url: https://github.com/ni/labview-icon-editor#labview-icon-editor
    about: "Check the documentation for common questions before opening an issue."

issue_templates:
  - name: ğŸ Bug Report
    path: bug_report.yaml
    description: "Report a reproducible issue."
    labels: ["bug"]
    
  - name: ğŸš€ Feature Request
    path: feature_request.yaml
    description: "Suggest a new feature or enhancement."
    labels: ["enhancement"]
